// Regenerates src/data/galleryImages.ts from the images on disk.
// Run from the project root:  node scripts/gen-gallery.mjs
//
// PRIORITY lists the tiles that must lead the gallery, in order; every other
// image in public/images/improved is appended after them (sorted by name).
// Natural pixel dimensions are read with sharp so the masonry reserves space.

import sharp from "sharp";
import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const PUB = "./public/images";
const IMPROVED = path.join(PUB, "improved");

const dims = async (file) => {
  const m = await sharp(file).metadata();
  return { w: m.width, h: m.height };
};

// `root:true` => file lives in /public/images directly, else in improved/.
const PRIORITY = [
  { f: "ChatGPT Image Sep 6, 2026, 04_13_40 PM.png" },
  { f: "ChatGPT Image Sep 6, 2026, 04_15_13 PM.png" },
  { f: "1.jpg", root: true },
  { f: "ChatGPT Image Sep 6, 2026, 04_21_26 PM.png" },
  { f: "ChatGPT Image Sep 6, 2026, 05_01_19 PM.png" },
  { f: "ChatGPT Image Sep 6, 2026, 04_42_50 PM.png" },
  { f: "ChatGPT Image Sep 6, 2026, 04_44_13 PM.png" },
  { f: "ChatGPT Image Sep 6, 2026, 03_59_53 PM.png" },
  { f: "017_1440437178083821.png" },
  { f: "ChatGPT Image Sep 6, 2026, 02_46_16 PM.png" },
  { f: "ChatGPT Image Sep 6, 2026, 02_58_30 PM (2).png" },
  { f: "ChatGPT Image Sep 6, 2026, 03_22_47 PM (2).png" },
];

const usedImproved = new Set(PRIORITY.filter((p) => !p.root).map((p) => p.f));
const allImproved = (await readdir(IMPROVED)).filter((f) => /\.(png|jpe?g|webp)$/i.test(f));
const rest = allImproved.filter((f) => !usedImproved.has(f)).sort();

const items = [];
for (const p of PRIORITY) {
  const abs = p.root ? path.join(PUB, p.f) : path.join(IMPROVED, p.f);
  const src = p.root ? `/images/${p.f}` : `/images/improved/${p.f}`;
  items.push({ src, ...(await dims(abs)) });
}
for (const f of rest) {
  items.push({ src: `/images/improved/${f}`, ...(await dims(path.join(IMPROVED, f))) });
}

const body = `// AUTO-GENERATED by scripts/gen-gallery.mjs — do not edit by hand.
// Showcase images for the gallery page, in display order. Dimensions are the
// images' natural pixel sizes, used to reserve masonry space (no layout shift).

export interface GalleryImage {
  src: string;
  w: number;
  h: number;
}

export const GALLERY_IMAGES: GalleryImage[] = [
${items.map((i) => `  { src: ${JSON.stringify(i.src)}, w: ${i.w}, h: ${i.h} },`).join("\n")}
];
`;

await writeFile("./src/data/galleryImages.ts", body, "utf8");
console.log(`Wrote ${items.length} images to src/data/galleryImages.ts`);
