// AUTO-GENERATED by scripts/gen-gallery.mjs — do not edit by hand.
// Showcase images for the gallery page, in display order. Dimensions are the
// images' natural pixel sizes, used to reserve masonry space (no layout shift).

export type GalleryCategory = "farm" | "processing" | "tech" | "moments";

export interface GalleryImage {
  src: string;
  category: GalleryCategory;
  w: number;
  h: number;
}

export const GALLERY_IMAGES: GalleryImage[] = [
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_13_40 PM.png", category: "processing", w: 1492, h: 1054 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_15_13 PM.png", category: "tech", w: 1492, h: 1054 },
  { src: "/images/1.jpg", category: "farm", w: 800, h: 449 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_21_26 PM.png", category: "farm", w: 1410, h: 1116 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_01_19 PM.png", category: "moments", w: 1551, h: 1014 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_42_50 PM.png", category: "farm", w: 1422, h: 1106 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_44_13 PM.png", category: "farm", w: 1536, h: 1024 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_59_53 PM.png", category: "moments", w: 1487, h: 1058 },
  { src: "/images/improved/017_1440437178083821.png", category: "moments", w: 1584, h: 993 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_46_16 PM.png", category: "processing", w: 1266, h: 1242 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_58_30 PM (2).png", category: "moments", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_22_47 PM (2).png", category: "moments", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_51_19 PM (1).png", category: "tech", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_51_19 PM (2).png", category: "tech", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_51_20 PM (3).png", category: "processing", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_51_20 PM (4).png", category: "tech", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_51_20 PM (5).png", category: "tech", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_58_30 PM (1).png", category: "moments", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_58_30 PM (3).png", category: "moments", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 02_58_31 PM (4).png", category: "farm", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_22_47 PM (1).png", category: "tech", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_22_47 PM (3).png", category: "moments", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_22_48 PM (4).png", category: "tech", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_22_48 PM (5).png", category: "tech", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_33_40 PM.png", category: "moments", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_35_55 PM (1).png", category: "farm", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_35_56 PM (2).png", category: "farm", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_35_56 PM (3).png", category: "farm", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_35_56 PM (4).png", category: "farm", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_35_57 PM (5).png", category: "farm", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_49_39 PM.png", category: "farm", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_50_30 PM.png", category: "moments", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_51_16 PM.png", category: "moments", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_52_35 PM.png", category: "moments", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_53_42 PM.png", category: "moments", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_54_57 PM.png", category: "moments", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_56_14 PM.png", category: "moments", w: 1703, h: 924 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_57_14 PM.png", category: "tech", w: 941, h: 1672 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 03_58_06 PM.png", category: "farm", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_02_49 PM.png", category: "farm", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_04_17 PM.png", category: "moments", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_06_45 PM.png", category: "farm", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_09_24 PM.png", category: "moments", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_10_54 PM.png", category: "processing", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_12_04 PM.png", category: "farm", w: 1086, h: 1448 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 04_41_28 PM.png", category: "moments", w: 1536, h: 1024 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_03_41 PM.png", category: "moments", w: 1447, h: 1087 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_05_36 PM.png", category: "moments", w: 1449, h: 1085 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_06_53 PM.png", category: "moments", w: 1447, h: 1087 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_11_04 PM.png", category: "moments", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_26_04 PM.png", category: "farm", w: 1672, h: 941 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_27_13 PM.png", category: "tech", w: 1448, h: 1086 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_28_56 PM.png", category: "farm", w: 1495, h: 1052 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_30_02 PM.png", category: "farm", w: 1549, h: 1015 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_31_19 PM.png", category: "processing", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 6, 2026, 05_32_55 PM.png", category: "farm", w: 1254, h: 1254 },
  { src: "/images/improved/ChatGPT Image Sep 7, 2026, 10_45_07 PM.png", category: "moments", w: 1448, h: 1086 },
];
